<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19237" started-at="2020-06-30T19:36:11 IST" finished-at="2020-06-30T19:36:30 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19237" started-at="2020-06-30T19:36:11 IST" finished-at="2020-06-30T19:36:30 IST">
      <class name="com.framework.WeatherCompareTest.WeatherTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.framework.WeatherCompareTest.WeatherTest@2bea5ab4]" name="initialize" is-config="true" duration-ms="8359" started-at="2020-06-30T19:36:11 IST" finished-at="2020-06-30T19:36:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="searchCityTemperatureTest()[pri:1, instance:com.framework.WeatherCompareTest.WeatherTest@2bea5ab4]" name="searchCityTemperatureTest" duration-ms="9871" started-at="2020-06-30T19:36:20 IST" finished-at="2020-06-30T19:36:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchCityTemperatureTest -->
        <test-method status="PASS" signature="dataFromAPI()[pri:2, instance:com.framework.WeatherCompareTest.WeatherTest@2bea5ab4]" name="dataFromAPI" duration-ms="173" started-at="2020-06-30T19:36:29 IST" finished-at="2020-06-30T19:36:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataFromAPI -->
        <test-method status="FAIL" signature="attributeComparator()[pri:3, instance:com.framework.WeatherCompareTest.WeatherTest@2bea5ab4]" name="attributeComparator" duration-ms="7" started-at="2020-06-30T19:36:30 IST" finished-at="2020-06-30T19:36:30 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.framework.WeatherCompareTest.WeatherTest.attributeComparator(WeatherTest.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- attributeComparator -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.framework.WeatherCompareTest.WeatherTest@2bea5ab4]" name="teardown" is-config="true" duration-ms="798" started-at="2020-06-30T19:36:30 IST" finished-at="2020-06-30T19:36:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.framework.WeatherCompareTest.WeatherTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
